### PR TITLE
fix root dir

### LINKED ISSUE #504: Error shared modules directory
I have a problem with the module ps_mbo.
If we shared the directory modules with a virtual link (on CICD for exemple), the module not working.

```
Compile Error: main(): Failed opening required '.../shared/public/modules/ps_mbo/../../vendor/autoload.php'
```

I will do a PR on this issue.

### PR DESCRIPTION
**Pull request by ytilotti**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 4.4.x
| Description?      | I have a problem with the module ps_mbo. If we shared the directory modules with a virtual link (on CICD for exemple), the module not working.
| Type?             | bug fix
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #504
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

File: bootstrap.php [hunk 1]
```diff
@@ -23,7 +23,7 @@
  * @copyright Since 2007 PrestaShop SA and Contributors
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  */
-$rootDir = getenv('_PS_ROOT_DIR_');
+$rootDir = _PS_ROOT_DIR_;
```
Comment (intraordinaire) [inline bootstrap.php:26]: To ensure that the constant is defined 
```suggestion
$rootDir = defined('_PS_ROOT_DIR_') ? _PS_ROOT_DIR_ : false;
```

**Review by intraordinaire — CHANGES_REQUESTED** [review]
Thanks for your contribution, just a little thing to fix for me.

**Comment by intraordinaire** [comment]
@ytilotti Looks good to me, but as PHPStan is failing, we need to investigate a bit to see what is going on and be sure that it's still working fine.

**Comment by ytilotti** [comment]
Hi team. No news?

**Comment by intraordinaire** [comment]
Hello @ytilotti 
We were in a rush to deliver some other features, but be sure that your PR is not forgotten.
We will do our best to validate it in the next weeks.

File: bootstrap.php [hunk 2]
```diff
@@ -24,7 +24,7 @@
  * @copyright Since 2007 PrestaShop SA and Contributors
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  */
-$rootDir = getenv('_PS_ROOT_DIR_');
+$rootDir = defined('_PS_ROOT_DIR_') ? _PS_ROOT_DIR_ : false;
```
Comment (intraordinaire) [inline bootstrap.php:27]:
```suggestion
$rootDir = defined('_PS_ROOT_DIR_') ? _PS_ROOT_DIR_ : getenv('_PS_ROOT_DIR_');
```
@ytilotti can you try with this ?
In some conditions, one may be empty, but not the other. So we ensure that you get the right value before fallbacking.

**Review by intraordinaire — CHANGES_REQUESTED** [review]

File: bootstrap.php (hunk 2 above)
Comment (ytilotti) [reply bootstrap.php:27]: `getenv('_PS_ROOT_DIR_')` can work? Because to get it will need to be set.

Comment (intraordinaire) [reply bootstrap.php:27]: Yes in some case. Anyway, it will return false if nothing found is found.
It seems to work well on my environment and on github actions. So I want to check if it's ok in your configuration too.

Comment (ytilotti) [reply bootstrap.php:27]: Yes will be ok because I match the first part.

**Review by sowbiba — APPROVED** [review]

**Comment by intraordinaire** [comment]
Thanks @ytilotti !

**Comment by ytilotti** [comment]
Thanks to you! I will be able to reactivate the update on this module.
